export const SET_USER_TOKEN = 'setUserToken'

export const SET_USER_TYPE = 'setUserType'
export const SET_TASK_EXECUTOR = 'SET_TASK_EXECUTOR'
export const SORT_TASK_EXECUTOR = 'SORT_TASK_EXECUTOR'
export const ADD_TASK_EXECUTOR = 'ADD_TASK_EXECUTOR'
export const DELETE_TASK_EXECUTOR = 'DELETE_TASK_EXECUTOR'
export const SET_TASK = 'SET_TASK'
export const SET_TASKTHEME = 'SET_TASKTHEME'
export const SET_CURRENT_PROJECT = 'SET_CURRENT_PROJECT'
export const SET_TASKID = 'SET_TASKID'

